#!/usr/bin/env python3
"""
Builds the launcher's test fixtures (run from anywhere):

  PANDORA LAUNCHER/src/tests/fixtures/tree/   - the files that go into the zip
  PANDORA LAUNCHER/src/tests/fixtures/packages.zip - real zip (deflate + stored,
      all three block types, non-ASCII names, nested paths, empty file)
  PANDORA LAUNCHER/src/tests/testzip.h        - the same zip embedded as a
      C array, so PandoraLauncher.exe --self-test can unpack a real package
      without shipping extra files
  PANDORA LAUNCHER/src/tests/expected.h       - name + SHA-256 + size of every
      member, so both the host tests and the .exe check the bytes they unpacked

The fixtures are deterministic: running this again produces identical output.
"""
import hashlib
import os
import random
import struct
import sys
import zipfile

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.dirname(HERE)
TESTS = os.path.join(SRC, "tests")
FIX = os.path.join(TESTS, "fixtures")
TREE = os.path.join(FIX, "tree")


def prng_bytes(seed, n):
    rnd = random.Random(seed)
    return bytes(rnd.getrandbits(8) for _ in range(n))


STORED_CONTENT = b"stored, not deflated\n" * 20


def build_tree():
    members = {}

    members["readme.txt"] = (
        "Pandora Launcher update package fixture.\r\n"
        "This file is small and compresses well.\r\n"
    ).encode("utf-8")

    members["lang/deutsch.txt"] = (
        "Grüße aus dem Pandora-Updater – Umlaute, ß und … Sonderzeichen.\n"
        "Windows Hello / Passkey Anmeldung.\n"
    ).encode("utf-8")

    members["ünïcødé-файл.txt"] = (
        "Non-ASCII member name, UTF-8 content: ключ – Schlüssel – 鍵\n"
    ).encode("utf-8")

    members["empty.txt"] = b""

    members["big.txt"] = (("A" * 900 + "B" * 90 + "Pandora\n") * 900).encode()  # ~900 KB

    members["bin/PandoraTool.dll"] = prng_bytes(1, 160 * 1024)       # incompressible

    mixed = bytearray()
    rnd = random.Random(2)
    for i in range(2200):
        if i % 3 == 0:
            mixed += b"MetaCore\x00\x01\x02" * 8
        else:
            mixed += bytes(rnd.getrandbits(8) for _ in range(12))
    members["bin/plugins/plugin_a.dat"] = bytes(mixed)

    members["sub/dir/deep.txt"] = b"deep file\n" * 50

    members["stored.bin"] = STORED_CONTENT

    for name, data in members.items():
        path = os.path.join(TREE, name.replace("/", os.sep))
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "wb") as f:
            f.write(data)
    return members


def build_zip(members):
    zpath = os.path.join(FIX, "packages.zip")
    # fixed timestamp so the archive is byte-identical between runs
    date_time = (2024, 1, 1, 0, 0, 0)
    with zipfile.ZipFile(zpath, "w", allowZip64=False) as z:
        levels = {"readme.txt": 1, "lang/deutsch.txt": 6, "ünïcødé-файл.txt": 9,
                  "big.txt": 9, "bin/PandoraTool.dll": 1, "empty.txt": 6}
        for name, data in members.items():
            if name == "stored.bin":
                continue
            zi = zipfile.ZipInfo(name, date_time)
            zi.compress_type = zipfile.ZIP_DEFLATED
            zi.external_attr = 0o644 << 16
            z.writestr(zi, data, compresslevel=levels.get(name, 6))
        # one member stored uncompressed (also exercises the copy path)
        zi = zipfile.ZipInfo("stored.bin", date_time)
        zi.compress_type = zipfile.ZIP_STORED
        z.writestr(zi, STORED_CONTENT)
    return zpath


def write_header(path, name, blob, comment):
    with open(path, "w") as f:
        f.write("/* Generated by src/tools/make-fixtures.py - do not edit. */\n")
        f.write("/* %s */\n" % comment)
        f.write("static const unsigned char %s[] = {\n" % name)
        for i in range(0, len(blob), 16):
            f.write("    " + ",".join("0x%02x" % b for b in blob[i:i + 16]) + ",\n")
        f.write("};\n")
        f.write("static const unsigned long %s_len = %dUL;\n" % (name, len(blob)))


def build_deflate_vectors():
    """Raw DEFLATE streams covering stored / fixed-Huffman / dynamic-Huffman."""
    import zlib

    vectors = []
    payloads = [
        ("empty", b""),
        ("repeating-text", (b"PandoraTool " * 40) + b"\n" * 20),
        ("binary-mixed", bytes((i * 7 + (i >> 3)) & 0xFF for i in range(4096))),
        ("random-10k", prng_bytes(7, 10 * 1024)),
        ("long-run", b"\x00" * 300 + b"\xff" * 300 + b"x" * 5000),
    ]
    strategies = [zlib.Z_DEFAULT_STRATEGY, zlib.Z_FIXED, zlib.Z_DEFAULT_STRATEGY,
                  zlib.Z_DEFAULT_STRATEGY, zlib.Z_FIXED]
    levels = [6, 9, 0, 9, 1]
    for (name, data), strat, lvl in zip(payloads, strategies, levels):
        co = zlib.compressobj(lvl, zlib.DEFLATED, -15, 9, strat)
        comp = co.compress(data) + co.flush()
        vectors.append((name, comp, data))
    return vectors


def write_deflate_header(path, vectors):
    with open(path, "w") as f:
        f.write("/* Generated by src/tools/make-fixtures.py - do not edit. */\n")
        f.write("typedef struct { const char *name; const unsigned char *comp;"
                " unsigned long complen; const unsigned char *plain;"
                " unsigned long plainlen; } deflate_vector;\n")
        for i, (name, comp, plain) in enumerate(vectors):
            f.write("static const unsigned char dv_comp_%d[] = {" % i)
            f.write(",".join("0x%02x" % b for b in comp))
            f.write("};\n")
            f.write("static const unsigned char dv_plain_%d[] = {" % i)
            f.write(",".join("0x%02x" % b for b in plain) if plain else "0")
            f.write("};\n")
        f.write("static const deflate_vector deflate_vectors[] = {\n")
        for i, (name, comp, plain) in enumerate(vectors):
            f.write('    { "%s", dv_comp_%d, %dUL, dv_plain_%d, %dUL },\n'
                    % (name, i, len(comp), i, len(plain)))
        f.write("};\n")
        f.write("#define DEFLATE_VECTOR_COUNT %d\n" % len(vectors))


def build_hostile_zip():
    """A package that tries to escape the install folder (must be rejected)."""
    import io
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w") as z:
        z.writestr("../evil.txt", b"you should never see this\n")
    return buf.getvalue()


def main():
    os.makedirs(FIX, exist_ok=True)
    os.makedirs(TREE, exist_ok=True)
    members = build_tree()
    zpath = build_zip(members)
    blob = open(zpath, "rb").read()
    write_header(os.path.join(TESTS, "testzip.h"), "test_zip", blob,
                 "a real update package: deflate + stored members, nested paths")

    vectors = build_deflate_vectors()
    write_deflate_header(os.path.join(TESTS, "deflate.h"), vectors)
    evil = build_hostile_zip()
    write_header(os.path.join(TESTS, "hostilezip.h"), "hostile_zip", evil,
                 "a package with a ../ escape entry: must be rejected")

    names = sorted(members.keys())
    with open(os.path.join(TESTS, "expected.h"), "w") as f:
        f.write("/* Generated by src/tools/make-fixtures.py - do not edit. */\n")
        f.write("typedef struct { const char *name; const char *sha256; unsigned long size; }"
                " expect_entry;\n")
        f.write("static const expect_entry expect_table[] = {\n")
        total = 0
        for n in names:
            d = members[n]
            f.write('    { "%s", "%s", %dUL },\n'
                    % (n, hashlib.sha256(d).hexdigest(), len(d)))
            total += len(d)
        f.write("};\n")
        f.write("#define EXPECT_COUNT %d\n" % len(names))
    print("fixtures: %d members, %d bytes raw, %d bytes zip; %d deflate vectors;"
          " hostile zip %d bytes"
          % (len(names), total, len(blob), len(vectors), len(evil)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
