/* Generated by src/tools/make-fixtures.py - do not edit. */
typedef struct { const char *name; const char *sha256; unsigned long size; } expect_entry;
static const expect_entry expect_table[] = {
    { "big.txt", "e95a336cc0b220aad4d0adec8273fef0f100050eec748595570368628fdb95a1", 898200UL },
    { "bin/PandoraTool.dll", "8aca17464a2128c5239983a930781bd9d60cec9a0f5766a3ffcb5d853754f59d", 163840UL },
    { "bin/plugins/plugin_a.dat", "76531857fc50ef0a3924586240cd91b48c5031a510c5fe76cb2200ad28ea538e", 82184UL },
    { "empty.txt", "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855", 0UL },
    { "lang/deutsch.txt", "90d8ea60513d72eb67cfb8d51d446c221b9ba9ae83a4f5fbf5698b4bdd10fa1e", 106UL },
    { "readme.txt", "464ebd95792e1b4f46a53d97799592f35da05bcb7439106ebbf89e4542a612a0", 83UL },
    { "stored.bin", "eb6fd24813f98ba20189a75e2e5b381e45af84090cd95344e795db456386d0f9", 420UL },
    { "sub/dir/deep.txt", "de4b27f31592f894edac8fe002b83de3256c69ce84c52c70e8e06f62f303e270", 500UL },
    { "ünïcødé-файл.txt", "f972c3568c2a5df50cd88d9f24ffb9b0e92a178e9350d20aaa0ff709fbb4d108", 70UL },
};
#define EXPECT_COUNT 9
